name: Static analysis, build & upload

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - master

jobs:
  static-analysis:
    name: Static analysis and build docs
    runs-on: windows-2022
    env:
      LLVM_INSTALL_DIR: "C:\\Program Files\\LLVM"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Use Python 3.12.6
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.6"
          architecture: "x64"
          cache: "pip"
          cache-dependency-path: "./requirements.txt"

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          aqtversion: "==3.1.*"
          version: "6.7.2"
          setup-python: 'false'
          archives: "qttools qtdeclarative qtbase qtsvg icu"
          documentation: false
          #doc-archives: "qtcore qtgui qtqml qtqmlcore qtqmlmodels qtquick qtquickcontrols qtquickdialogs qtsvg"
          cache: true

      - name: Build sdist
        run: |
          pip install build
          $Env:PIP_EXTRA_INDEX_URL = "https://download.qt.io/official_releases/QtForPython/"
          python -m build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: QuickGraphLib-sdist
          path: dist/*.tar.gz

      - uses: KyleMayes/install-llvm-action@v2
        with:
          version: "18.1.8"
          directory: "C:\\Program Files\\LLVM"

      - name: "check llvm"
        run: echo "LLVM_INSTALL_DIR is $LLVM_INSTALL_DIR"

      - name: Setup env
        run: .\setup_venv

      - name: Run linting on all files
        run: |
          .\activate_venv.ps1
          pre-commit run --all-files --show-diff-on-failure


  build-wheels:
    name: Build wheels on ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      LLVM_INSTALL_DIR: "C:\\Program Files\\LLVM"
    needs: static-analysis
    steps:
      - name: "Download sdist"
        uses: actions/download-artifact@v4
        with:
          name: QuickGraphLib-sdist
          path: dist

      - name: Rename sdist package
        run: mv dist/*.tar.gz sdist.tar.gz

      - uses: KyleMayes/install-llvm-action@v2
        if: ${{ matrix.os }} == 'windows-latest'
        with:
          version: "18.1.8"
          directory: "C:\\Program Files\\LLVM"

      - name: "check llvm"
        run: echo "LLVM_INSTALL_DIR is $LLVM_INSTALL_DIR"

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21.1
        with:
          package-dir: sdist.tar.gz

      - uses: actions/upload-artifact@v4
        with:
          name: QuickGraphLib-wheel-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  upload-github:
    name: Upload to GitHub
    runs-on: ubuntu-latest
    needs:
      - build-wheels
      - static-analysis
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    environment:
      name: github-release
      url: ${{ steps.deployment.outputs.url }}
    concurrency:
      group: "deploy-github"
      cancel-in-progress: false
    steps:
      - name: "Download wheels"
        uses: actions/download-artifact@v4
        with:
          pattern: QuickGraphLib-wheel-*
          path: dist
          merge-multiple: true

      - name: "Download sdist"
        uses: actions/download-artifact@v4
        with:
          name: QuickGraphLib-sdist
          path: dist

      - name: Release
        id: deployment
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*
          generate_release_notes: true
