name: Build, static analysis, tests & upload

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - '*'
    branches:
      - master

jobs:
  build:
    name: Build, static analysis & tests
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Use Python 3.10.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.10"
          architecture: "x64"
          cache: "pip"
          cache-dependency-path: "./pyproject.toml"

      - name: Setup env
        run: .\setup_venv

      - name: Run linting on all files
        run: |
          .\activate_venv.ps1
          pre-commit run --all-files --show-diff-on-failure

      - name: Build wheel
        run: |
          .\activate_venv.ps1
          python -m build

      - uses: actions/upload-artifact@v4
        with:
          name: QuickGraphLib-wheels
          path: dist/*

  upload:
    name: Upload to PyPI
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/QuickGraphLib
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: QuickGraphLib-wheels
          path: dist

      - name: Display structure of downloaded files
        run: ls -R

      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
