name: Build, static analysis & tests

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - '*'
    branches:
      - master

jobs:     
  static_analysis:
    name: Build, static analysis & tests
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Use Python 3.10.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.10"
          architecture: "x64"
          cache: "pip"
          cache-dependency-path: "./pyproject.toml"

      - name: Setup env
        run: .\setup_venv

      - name: Run linting on all files
        run: |
          .\activate_venv.ps1
          pre-commit run --all-files --show-diff-on-failure

      - name: Build wheel
        run: |
          .\activate_venv.ps1
          python -m build
      - uses: actions/upload-artifact@v4
        with:
          name: QuickGraphLib-wheels
          path: dist/*
