name: Static analysis, build & upload

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - '*'
    branches:
      - master

jobs:
  static_analysis:
    name: Static analysis
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Python 3.10.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.11"
          architecture: "x64"
          cache: "pip"
          cache-dependency-path: "./requirements.txt"

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          version: '6.5.3'
          archives: 'qttools qtdeclarative qtbase qtsvg icu'
          cache: true
          tools: 'tools_cmake'

      - name: Setup env
        run: .\setup_venv

      - name: Run linting on all files
        run: |
          .\activate_venv.ps1
          pre-commit run --all-files --show-diff-on-failure

  build-wheels:
    name: Build wheels on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    needs: static_analysis
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Mess with tmpdir
        if: matrix.os == 'windows-latest'
        run: |
          # Stupid Windows/MSCV/MSBuild file path length issues
          mkdir C:\tmp
          echo "TMPDIR=C:\tmp" > $env:GITHUB_ENV

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19.1

      - uses: actions/upload-artifact@v4
        with:
          name: QuickGraphLib-wheel-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  build-docs:
    name: Build docs
    runs-on: windows-latest # TODO use ubuntu
    needs: static_analysis
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Use Python 3.10.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.11"
          architecture: "x64"
          cache: "pip"
          cache-dependency-path: "./requirements.txt"
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          version: '6.5.3'
          archives: 'qttools qtdeclarative qtbase qtsvg icu'
          documentation: true
          doc-archives: 'qtcore qtgui qtqml qtqmlcore qtqmlmodels qtquick qtquickcontrols qtquickdialogs qtsvg'
          cache: true
          tools: 'tools_cmake'

      - name: Setup env
        run: .\setup_venv

      - name: Build docs
        run: |
          .\activate_venv.ps1
          python docs/build_docs.py

      - uses: actions/upload-artifact@v4
        with:
          name: QuickGraphLib-docs
          path: dist/docs/*

      - name: Build sdist
        run: |
          .\activate_venv.ps1
          python -m build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: QuickGraphLib-sdist
          path: dist/*.tar.gz

  upload-pypi:
    name: Upload to PyPI
    runs-on: ubuntu-latest
    needs:
      - build-wheels
      - build-docs
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    environment:
      name: pypi
      url: https://pypi.org/p/QuickGraphLib
    permissions:
      id-token: write
    concurrency:
      group: "deploy-pypi"
      cancel-in-progress: false
    steps:
      - name: "Download wheels"
        uses: actions/download-artifact@v4
        with:
          pattern: QuickGraphLib-wheel-*
          path: dist
          merge-multiple: true

      - name: "Download sdist"
        uses: actions/download-artifact@v4
        with:
          name: QuickGraphLib-sdist
          path: dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  upload-docs:
    name: Upload to GitHub Pages
    runs-on: ubuntu-latest
    needs: build-docs
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: "deploy-pages"
      cancel-in-progress: false
    steps:
      - name: "Download docs"
        uses: actions/download-artifact@v4
        with:
          name: QuickGraphLib-docs
          path: docs

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  upload-github:
    name: Upload to GitHub
    runs-on: ubuntu-latest
    needs:
      - build-wheels
      - build-docs
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    environment:
      name: github-release
      url: ${{ steps.deployment.outputs.url }}
    concurrency:
      group: "deploy-github"
      cancel-in-progress: false
    steps:
      - name: "Download wheels"
        uses: actions/download-artifact@v4
        with:
          pattern: QuickGraphLib-wheel-*
          path: dist
          merge-multiple: true

      - name: "Download sdist"
        uses: actions/download-artifact@v4
        with:
          name: QuickGraphLib-sdist
          path: dist

      - name: "Download docs"
        uses: actions/download-artifact@v4
        with:
          name: QuickGraphLib-docs
          path: docs

      - name: Zip docs
        run: zip -r docs.zip docs

      - name: Release
        id: deployment
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*
            docs.zip
          generate_release_notes: true
